baseurl = "https://vadim.me"
title = "Vadim Liventsev"
theme = "hugo-coder"
languagecode = "en"
defaultcontentlanguage = "en"

paginate = 20

pygmentsstyle = "bw"
pygmentscodefences = true
pygmentscodefencesguesssyntax = true

[params]
  author = "Vadim Liventsev"
  info = ["AI Developer", "PhD @ TU/e & Philips"]
  description = ""
  keywords = "blog,developer,personal"
  gravatar = "hi@vadim.me"

  #favicon_32 = "/img/favicon-32x32.png"
  #favicon_16 = "/img/favicon-16x16.png"

  footercontent = "42"
  hideFooter = true
  hideCredits = false
  hideCopyright = false
  since = 2019

  enableTwemoji = true

  colorScheme = "auto"
  hidecolorschemetoggle = false

 # customCSS = ["css/custom.css"]
 # customSCSS = ["scss/custom.scss"]
 # customJS = ["js/custom.js"]

[taxonomies]
  category = "categories"
  series = "series"
  tag = "tags"
  author = "authors"

# Social links
[[params.social]]
  name = "Github"
  icon = "fa fa-github fa-2x"
  weight = 2
  url = "https://github.com/vadim0x60"
[[params.social]]
  name = "Telegram"
  icon = "fa fa-telegram fa-2x"
  weight = 2
  url = "https://t.me/vadim0x60"
[[params.social]]
  name = "Google Scholar"
  icon = "fa fa-google fa-2x"
  weight = 2
  url = "https://scholar.google.com/citations?user=tpB0Uw8AAAAJ"

[markup.goldmark.renderer]
unsafe = true

# Menu links
[[menu.main]]
  name = "Blog"
  weight = 1
  url  = "posts/"
[[menu.main]]
  name = "About"
  weight = 2
  url = "about/"
